hmrc/manage-transit-movements-unloading-frontend

app/controllers/UnloadingSummaryController.scala
app/views/UnloadingSummaryView.scala.html
conf/app.routes
test/controllers/UnloadingSummaryControllerSpec.scala

Ensuring button triggers a form action.

---

app/connectors/ReferenceDataConnector.scala
app/controllers/AddUnloadingCommentsYesNoController.scala
app/controllers/DateGoodsUnloadedController.scala
app/controllers/UnloadingFindingsController.scala
app/controllers/UnloadingRemarksSentController.scala
app/controllers/actions/UnloadingPermissionAction.scala
app/forms/AddUnloadingCommentsYesNoFormProvider.scala
app/navigation/Navigator.scala
app/pages/AddUnloadingCommentsYesNoPage.scala
app/utils/AnswersHelper.scala
app/utils/CheckYourAnswersHelper.scala
app/utils/SummaryListRowHelper.scala
app/viewModels/CheckYourAnswersViewModel.scala
app/views/AddUnloadingCommentsYesNoView.scala.html
app/views/utils/ViewUtils.scala
conf/app.routes
conf/messages.en
test/controllers/AddUnloadingCommentsYesNoControllerSpec.scala
test/navigation/NavigatorSpec.scala
test/pages/AddUnloadingCommentsYesNoPageSpec.scala
test/pages/behaviours/PageBehaviours.scala
test/utils/CheckYourAnswersHelperSpec.scala
test/viewModels/CheckYourAnswersViewModelSpec.scala
test/views/AddUnloadingCommentsYesNoViewSpec.scala

https://jira.tools.tax.service.gov.uk/browse/CTCP-2773

CTCP-2773: Add unloading comments yes no page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/partials/_declaration_summary.scss

Fixing UR banner styling.

---

app/controllers/transport/equipment/GoodsReferenceController.scala
app/forms/SelectableFormProvider.scala
app/models/reference/Country.scala
app/models/reference/Item.scala
app/pages/GoodsReferencePage.scala
app/viewModels/transportEquipment/GoodsReferenceViewModel.scala
app/views/houseConsignment/index/items/GoodsReferenceView.scala.html
app/views/utils/ViewUtils.scala
conf/app.routes
conf/messages.en
test/controllers/transportEquipment/GoodsReferenceControllerSpec.scala
test/generators/ModelGenerators.scala
test/views/transportEquipment/GoodsReferenceViewSpec.scala

CTCP-4603: Goods reference

---

app/controllers/documents/AdditionalInformationController.scala
app/forms/AdditionalInformationFormProvider.scala
app/pages/documents/AdditionalInformationPage.scala
app/viewModels/documents/AdditionalInformationViewModel.scala
app/views/documents/AdditionalInformationView.scala.html
conf/app.documents.routes
conf/messages.en
test/controllers/documents/AdditionalInformationControllerSpec.scala
test/forms/AdditionalInformationFormProviderSpec.scala
test/generators/ViewModelGenerators.scala
test/pages/documents/AdditionalInformationPageSpec.scala
test/viewModels/documents/AdditionalInformationViewModelSpec.scala
test/views/documents/AdditionalInformationViewSpec.scala

CTCP-4615: Additional Information Page

---

app/controllers/transportEquipment/index/ApplyAnotherItemController.scala
app/viewModels/transportEquipment/SelectItemsViewModel.scala
app/views/transport/equipment/ApplyAnotherItemView.scala.html
test/controllers/transportEquipment/index/ApplyAnotherItemControllerSpec.scala
test/views/transportEquipment/index/ApplyAnotherItemViewSpec.scala

CTCP-4604: fix

---

app/utils/UnloadingAnswersHelper.scala
conf/messages.en
test/utils/HouseConsignmentAnswersHelperSpec.scala
test/utils/RowActions.scala
test/utils/UnloadingAnswersHelperSpec.scala
test/utils/UnloadingFindingsAnswersHelperSpec.scala

CTCP-4875: Gross/Net Mass change links

---

app/pages/houseConsignment/index/items/DangerousGoodsPage.scala
app/pages/sections/houseConsignment/index/items/dangerousGoods/DangerousGoodsSection.scala
app/utils/answersHelpers/consignment/HouseConsignmentAnswersHelper.scala
app/utils/answersHelpers/consignment/houseConsignment/ConsignmentItemAnswersHelper.scala
app/utils/answersHelpers/consignment/houseConsignment/item/DangerousGoodsAnswerHelper.scala
app/utils/transformers/CommodityTransformer.scala
app/utils/transformers/DangerousGoodsTransformer.scala
conf/messages.en
test/base/SpecBase.scala
test/utils/answersHelpers/consignment/houseConsignment/item/DangerousGoodsAnswersHelperSpec.scala
test/utils/transformers/CommodityTransformerSpec.scala
test/utils/transformers/DangerousGoodsTransformerSpec.scala

UN number 1 & UN number 2 rows

CTCP-4885: Dangerous Goods

---

app/pages/houseConsignment/index/items/document/DocumentReferenceNumberPage.scala
app/pages/sections/houseConsignment/index/items/documents/DocumentSection.scala
app/pages/sections/houseConsignment/index/items/documents/DocumentsSection.scala
app/utils/answersHelpers/consignment/HouseConsignmentAnswersHelper.scala
app/utils/answersHelpers/consignment/houseConsignment/ConsignmentItemAnswersHelper.scala
app/utils/answersHelpers/consignment/houseConsignment/item/DocumentAnswersHelper.scala
app/utils/transformers/AdditionalReferencesTransformer.scala
app/utils/transformers/ConsignmentItemTransformer.scala
app/utils/transformers/ConsignmentTransformer.scala
app/utils/transformers/DocumentsTransformer.scala
conf/messages.en
test/utils/answersHelpers/consignment/HouseConsignmentAnswersHelperSpec.scala
test/utils/answersHelpers/consignment/houseConsignment/ConsignmentItemAnswersHelperSpec.scala
test/utils/answersHelpers/consignment/houseConsignment/item/DocumentAnswersHelperSpec.scala
test/utils/transformers/AdditionalReferencesTransformerSpec.scala
test/utils/transformers/ConsignmentItemTransformerSpec.scala
test/utils/transformers/ConsignmentTransformerSpec.scala
test/utils/transformers/DocumentsTransformerSpec.scala

CTCP-4877: CONSIGNMENT ITEM.SUPPORTING DOCUMENT and CONSIGNMENT ITEM.TRANSPORT DOCUMENT

---

app/models/Address.scala
app/pages/ConsigneeAddressPage.scala
app/pages/ConsigneeCountryPage.scala
app/utils/answersHelpers/ConsignmentAnswersHelper.scala
app/utils/answersHelpers/HolderOfTheTransitProcedureHelper.scala
app/utils/answersHelpers/SummaryListRowHelper.scala
app/utils/answersHelpers/consignment/HouseConsignmentAnswersHelper.scala
app/utils/transformers/ConsigneeTransformer.scala
app/viewModels/HouseConsignmentViewModel.scala
conf/messages.en
test/generators/ModelGenerators.scala
test/utils/answersHelpers/consignment/HouseConsignmentAnswersHelperSpec.scala
test/utils/transformers/ConsigneeTransformerSpec.scala
test/utils/transformers/HouseConsignmentsTransformerSpec.scala

CTCP-4888: Consignee country/address

---

app/models/DynamicAddress.scala
app/models/package.scala
app/pages/consignor/CountryPage.scala
app/pages/sections/ConsignorSection.scala
app/utils/answersHelpers/ConsignmentAnswersHelper.scala
app/utils/answersHelpers/HolderOfTheTransitProcedureHelper.scala
app/utils/answersHelpers/consignment/ConsignorAnswersHelper.scala
app/utils/transformers/ConsignmentTransformer.scala
app/utils/transformers/ConsignorTransformer.scala
app/viewModels/UnloadingFindingsViewModel.scala
conf/messages.en
test/pages/consignor/CountryPageSpec.scala
test/utils/answersHelpers/ConsignmentAnswersHelperSpec.scala
test/utils/answersHelpers/consignment/ConsignorAnswersHelperSpec.scala
test/utils/transformers/ConsignmentTransformerSpec.scala
test/utils/transformers/ConsignorTransformerSpec.scala
test/viewModels/UnloadingFindingsViewModelSpec.scala

CTCP-4868 : IE043.CONSIGNMENT.CONSIGNOR

---

app/pages/incident/transhipment/IdentificationPage.scala
app/pages/incident/transhipment/NationalityPage.scala
app/utils/answersHelpers/ConsignmentAnswersHelper.scala
app/utils/answersHelpers/consignment/IncidentAnswersHelper.scala
app/utils/answersHelpers/consignment/transhipment/TranshipmentAnswersHelper.scala
app/utils/transformers/IncidentsTransformer.scala
app/utils/transformers/TranshipmentTransformer.scala
conf/messages.en
test/generators/MessagesModelGenerators.scala
test/pages/incident/transhipment/IdentificationPageSpec.scala
test/pages/incident/transhipment/NationalityPageSpec.scala
test/utils/answersHelpers/consignment/IncidentAnswersHelperSpec.scala
test/utils/answersHelpers/consignment/transhipment/TranshipmentAnswersHelperSpec.scala
test/utils/transformers/DocumentsTransformerSpec.scala
test/utils/transformers/IncidentsTransformerSpec.scala
test/utils/transformers/TranshipmentTransformerSpec.scala

CTCP-4891: IE43/44 - Cross Check - Import IE43 Data+ store+ transform+ display -IE043.CONSIGNMENT.INCIDENT.TRANSHIPMENT

---

app/controllers/departureMeansOfTransport/RemoveDepartureMeansOfTransportYesNoController.scala
app/models/TransportMeans.scala
app/viewModels/components/InputYesNoViewModel.scala
app/views/RemoveDepartureMeansOfTransportYesNoView.scala.html
conf/messages.en
test/controllers/RemoveDepartureMeansOfTransportYesNoControllerSpec.scala
test/models/TransportMeansSpec.scala
test/views/behaviours/ViewBehaviours.scala
test/views/departureMeansOfTransport/RemoveDepartureMeansOfTransportYesNoViewSpec.scala

Optional inset text on remove dtm page.

---

app/utils/answersHelpers/consignment/HouseConsignmentAnswersHelper.scala
app/viewModels/HouseConsignmentViewModel.scala
test/utils/answersHelpers/consignment/HouseConsignmentAnswersHelperSpec.scala
test/viewModels/HouseConsignmentViewModelSpec.scala

CTCP-4560: update link to be outside item section

---

conf/messages.en
test/models/TransportEquipmentSpec.scala
test/viewModels/transportEquipment/AddAnotherEquipmentViewModelSpec.scala

Change container to Container in inset text

Ctcp 4692 bug

---

app/viewModels/components/InputYesNoViewModel.scala
app/views/additionalReference/index/AddAnotherAdditionalReferenceView.scala.html
app/views/components/InputYesNo.scala.html
app/views/documents/AddAnotherDocumentView.scala.html
app/views/houseConsignment/index/items/additionalReference/AddAnotherAdditionalReferenceView.scala.html
app/views/houseConsignment/index/items/document/AddAnotherDocumentView.scala.html
app/views/transportEquipment/AddAnotherEquipmentView.scala.html
app/views/utils/ViewUtils.scala
conf/application.conf

'Add another' paragraph text moved between h2 and radios.

---

app/controllers/houseConsignment/index/GrossWeightController.scala
app/pages/houseConsignment/index/GrossWeightPage.scala
app/views/houseConsignment/index/GrossWeightView.scala.html
conf/app.houseConsignment.index.routes
conf/app.routes
conf/messages.en
test/controllers/houseConsignment/index/GrossWeightControllerSpec.scala
test/pages/houseConsignment/index/GrossWeightPageSpec.scala
test/views/houseConsignment/index/GrossWeightViewSpec.scala

CTCP-4897: GrossWeight Page HC level

---

app/pages/houseConsignment/index/additionalinformation/HouseConsignmentAdditionalInformationCodePage.scala
app/pages/houseConsignment/index/additionalinformation/HouseConsignmentAdditionalInformationTextPage.scala
app/pages/houseConsignment/index/items/additionalinformation/HouseConsignmentItemAdditionalInformationCodePage.scala
app/pages/houseConsignment/index/items/additionalinformation/HouseConsignmentItemAdditionalInformationTextPage.scala
app/pages/sections/houseConsignment/index/additionalInformation/AdditionalInformationListSection.scala
app/pages/sections/houseConsignment/index/additionalInformation/AdditionalInformationSection.scala
app/utils/answersHelpers/consignment/HouseConsignmentAnswersHelper.scala
app/utils/answersHelpers/consignment/houseConsignment/HouseConsignmentAdditionalInformationAnswersHelper.scala
app/utils/transformers/AdditionalInformationTransformer.scala
app/utils/transformers/HouseConsignmentsTransformer.scala
app/viewModels/HouseConsignmentViewModel.scala
test/pages/houseConsignment/index/additionalinformation/HouseConsignmentAdditionalInformationCodePageSpec.scala
test/pages/houseConsignment/index/additionalinformation/HouseConsignmentAdditionalInformationTextPageSpec.scala
test/pages/houseConsignment/index/items/additionalinformation/HouseConsignmentItemAdditionalInformationCodePageSpec.scala
test/pages/houseConsignment/index/items/additionalinformation/HouseConsignmentItemAdditionalInformationTextPageSpec.scala
test/utils/answersHelpers/consignment/HouseConsignmentAnswersHelperSpec.scala
test/utils/answersHelpers/consignment/houseConsignment/HouseConsignmentAdditionalInformationAnswersHelperSpec.scala
test/utils/transformers/AdditionalInformationTransformerSpec.scala
test/utils/transformers/HouseConsignmentsTransformerSpec.scala
test/viewModels/HouseConsignmentViewModelSpec.scala

CTCP-4892: Transform AdditionalInformation HC level

---

app/controllers/houseConsignment/index/items/AddCombinedNomenclatureCodeYesNoController.scala
app/controllers/houseConsignment/index/items/AddCommodityCodeYesNoController.scala
app/controllers/houseConsignment/index/items/packages/AddNumberOfPackagesYesNoController.scala
app/controllers/houseConsignment/index/items/packages/AddPackageShippingMarkYesNoController.scala
app/controllers/houseConsignment/index/items/packages/RemovePackageTypeYesNoController.scala
app/navigation/houseConsignment/index/items/AddPackagesNavigator.scala
app/navigation/houseConsignment/index/items/HouseConsignmentItemNavigator.scala
test/base/AppWithDefaultMockFixtures.scala
test/navigation/houseConsignment/index/items/AddPackagesNavigatorSpec.scala
test/navigation/houseConsignment/index/items/HouseConsignmentItemNavigatorSpec.scala

This branch needs to be merged after add-remove-item-nav branch

Ctcp 5191 - IE043/44 - Cross Check Page - Add/Remove Items - Navigation (5/5)

---

app/utils/answersHelpers/consignment/HouseConsignmentAnswersHelper.scala
conf/messages.en
test/utils/answersHelpers/consignment/HouseConsignmentAnswersHelperSpec.scala

CTCP-4896: IE043.CONSIGNMENT.HOUSE CONSIGNMENT.CONSIGNOR

---

conf/messages.en
test/views/houseConsignment/AddAnotherHouseConsignmentViewSpec.scala

[CTCP-5034](https://jira.tools.tax.service.gov.uk/browse/CTCP-5034)

CTCP-5034: Added empty state content for AddAnotherHouseConsignment

---

app/viewModels/components/InputSelectViewModel.scala
app/views/houseConsignment/index/items/packages/PackageTypeView.scala.html
conf/logback.xml
test/views/houseConsignment/index/items/packages/PackageTypeViewSpec.scala

CTCP-5120: Package type content update

---

app/assets/javascripts/ctc.js

https://jira.tools.tax.service.gov.uk/browse/CTCP-5512

CTCP-5512 Remove back link handling that introduced the bug

---

app/controllers/departureMeansOfTransport/RemoveDepartureMeansOfTransportYesNoController.scala
app/controllers/houseConsignment/index/items/RemoveConsignmentItemYesNoController.scala
app/views/houseConsignment/index/items/RemoveConsignmentItemYesNoView.scala.html
app/views/transportEquipment/index/seals/RemoveSealYesNoView.scala.html
conf/messages.en
test/controllers/RemoveDepartureMeansOfTransportYesNoControllerSpec.scala
test/controllers/houseConsignment/index/items/RemoveConsignmentItemYesNoControllerSpec.scala
test/views/houseConsignment/index/items/RemoveConsignmentItemYesNoViewSpec.scala
test/views/transportEquipment/index/seals/RemoveSealYesNoViewSpec.scala

https://jira.tools.tax.service.gov.uk/browse/CTCP-5450

CTCP-5450: remove screen content updates

---

app/controllers/SealsReplacedByCustomsAuthorityYesNoController.scala
app/pages/SealsReplacedByCustomsAuthorityYesNoPage.scala
app/views/SealsReplacedByCustomsAuthorityYesNoView.scala.html
conf/app.routes
conf/messages.en
test/controllers/SealsReplacedByCustomsAuthorityYesNoControllerSpec.scala
test/pages/SealsReplacedByCustomsAuthorityYesNoPageSpec.scala
test/views/SealsReplacedByCustomsAuthorityYesNoSpec.scala

CTCP-5511: have the seals been replaced by the customs authority

---

app/controllers/CannotUseRevisedUnloadingProcedureController.scala
app/navigation/Navigation.scala
app/views/CannotUseRevisedUnloadingProcedureView.scala.html
conf/app.routes
conf/messages.en
test/controllers/CannotUseRevisedUnloadingProcedureControllerSpec.scala
test/navigation/NavigationSpec.scala
test/views/CannotUseRevisedUnloadingProcedureViewSpec.scala

CTCP-5876: Create CannotUseRevisedUnloadingProcedure page

---

app/config/FrontendAppConfig.scala
app/connectors/ReferenceDataConnector.scala
app/models/reference/DocTypeExcise.scala
app/services/ReferenceDataService.scala
app/utils/transformers/HolderOfTheTransitProcedureTransformer.scala
app/utils/transformers/package.scala
conf/application.conf
it/test/connectors/ReferenceDataConnectorSpec.scala
it/test/itbase/FakeAsyncCacheApi.scala
project/AppDependencies.scala
test/base/AppWithDefaultMockFixtures.scala
test/base/FakeAsyncCacheApi.scala
test/models/reference/DocTypeExciseSpec.scala
test/services/AdditionalReferencesServiceSpec.scala
test/services/ReferenceDataServiceSpec.scala
test/views/templates/MainTemplateSpec.scala

CTCP-5995: Caching reference data results for 60 seconds.

---

app/utils/answersHelpers/CheckYourAnswersHelper.scala
app/viewModels/CheckYourAnswersViewModel.scala
conf/messages.en
test/utils/answersHelpers/CheckYourAnswersHelperSpec.scala
test/viewModels/CheckYourAnswersViewModelSpec.scala

CTCP-6043: Add new page to CYA

---

app/controllers/CannotUseRevisedUnloadingProcedureController.scala
app/controllers/NewAuthYesNoController.scala
app/controllers/PhotographExternalSealController.scala
app/controllers/RevisedUnloadingProcedureConditionsYesNoController.scala
app/controllers/RevisedUnloadingProcedureUnmetConditionsController.scala
app/controllers/UnloadingGuidanceController.scala
app/controllers/actions/SpecificDataRequiredAction.scala
app/models/UnloadingSubmissionValues.scala
app/navigation/Navigation.scala
app/pages/DidUserChooseNewProcedurePage.scala
app/pages/LargeUnsealedGoodsRecordDiscrepanciesYesNoPage.scala
app/pages/NewAuthYesNoPage.scala
app/pages/RevisedUnloadingProcedureConditionsYesNoPage.scala
app/services/UsersAnswersService.scala
app/services/submission/SubmissionService.scala
project/AppDependencies.scala
test/controllers/CannotUseRevisedUnloadingProcedureControllerSpec.scala
test/controllers/NewAuthYesNoControllerSpec.scala
test/controllers/PhotographExternalSealControllerSpec.scala
test/controllers/RevisedUnloadingProcedureConditionsYesNoControllerSpec.scala
test/controllers/RevisedUnloadingProcedureUnmetConditionsControllerSpec.scala
test/controllers/UnloadingGuidanceControllerSpec.scala
test/models/UnloadingSubmissionValuesSpec.scala
test/navigation/NavigationSpec.scala
test/pages/DidUserChooseNewProcedurePageSpec.scala
test/pages/LargeUnsealedGoodsRecordDiscrepanciesYesNoPageSpec.scala
test/pages/NewAuthYesNoPageSpec.scala
test/pages/RevisedUnloadingProcedureConditionsYesNoPageSpec.scala
test/services/UsersAnswersServiceSpec.scala
test/services/submission/SubmissionServiceSpec.scala

https://jira.tools.tax.service.gov.uk/browse/CTCP-6044

CTCP-6044 Update navigation

---

app/services/submission/SubmissionService.scala
test/services/submission/SubmissionServiceSpec.scala

https://jira.tools.tax.service.gov.uk/browse/CTCP-6050?focusedId=2375102&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2375102

CTCP-6050 Fix submission for revised route

---

app/forms/mappings/LocalDateFormatter.scala
app/views/components/InputDate.scala.html
app/views/utils/ViewUtils.scala
test/forms/behaviours/DateBehaviours.scala
test/forms/mappings/LocalDateFormatterSpec.scala
test/views/behaviours/DateInputViewBehaviour.scala

- Only the specific fields that have an error are highlighted in red
- For a min/max error, all fields are highlighted in red

CTCP-6341: Amended logic to work with withDayMonthYearFormField

---

app/navigation/Navigation.scala
test/navigation/NavigationSpec.scala

https://github.com/user-attachments/assets/a589823f-64ea-41d4-b268-caf914df9680

CTCP-6352: Updating CheckMode navigation.

---

app/config/FrontendAppConfig.scala
app/pages/CountryOfRoutingPage.scala
app/pages/UniqueConsignmentReferencePage.scala
app/pages/houseConsignment/index/UniqueConsignmentReferencePage.scala
app/pages/houseConsignment/index/items/UniqueConsignmentReferencePage.scala
app/pages/sections/CountriesOfRoutingSection.scala
app/pages/sections/CountryOfRoutingSection.scala
app/utils/answersHelpers/ConsignmentAnswersHelper.scala
app/utils/answersHelpers/consignment/CountryOfRoutingAnswersHelper.scala
app/utils/answersHelpers/consignment/HouseConsignmentAnswersHelper.scala
app/utils/answersHelpers/consignment/houseConsignment/ConsignmentItemAnswersHelper.scala
app/viewModels/HouseConsignmentViewModel.scala
app/viewModels/UnloadingFindingsViewModel.scala
conf/application.conf
conf/messages.en
test/pages/CountryOfRoutingPageSpec.scala
test/pages/UniqueConsignmentReferencePageSpec.scala
test/pages/houseConsignment/index/UniqueConsignmentReferencePageSpec.scala
test/pages/houseConsignment/index/items/UniqueConsignmentReferencePageSpec.scala
test/resources/application.conf
test/utils/answersHelpers/ConsignmentAnswersHelperSpec.scala
test/utils/answersHelpers/consignment/CountryOfRoutingAnswersHelperSpec.scala
test/utils/answersHelpers/consignment/HouseConsignmentAnswersHelperSpec.scala
test/utils/answersHelpers/consignment/houseConsignment/ConsignmentItemAnswersHelperSpec.scala
test/viewModels/HouseConsignmentViewModelSpec.scala
test/viewModels/UnloadingFindingsViewModelSpec.scala

Design & Content - Cross Check Page (Country of routing consignment + Reference number UCR)

CTCP- 6417

---

app/connectors/ReferenceDataConnector.scala
app/controllers/houseConsignment/index/items/CommodityCodeController.scala
app/controllers/houseConsignment/index/items/CustomsUnionAndStatisticsCodeController.scala
app/forms/CommodityCodeFormProvider.scala
app/models/reference/HSCode.scala
app/services/ReferenceDataService.scala
app/viewModels/houseConsignment/index/items/CommodityCodeViewModel.scala
conf/messages.en
it/test/connectors/ReferenceDataConnectorSpec.scala
test/controllers/houseConsignment/index/items/CommodityCodeControllerSpec.scala
test/controllers/houseConsignment/index/items/CustomsUnionAndStatisticsCodeControllerSpec.scala
test/forms/CommodityCodeFormProviderSpec.scala
test/generators/ModelGenerators.scala
test/generators/ViewModelGenerators.scala
test/models/reference/HSCodeSpec.scala
test/services/ReferenceDataServiceSpec.scala
test/viewModels/houseConsignment/index/items/CommodityCodeViewModelSpec.scala
test/views/houseConsignment/index/items/CommodityCodeViewSpec.scala

CTCP-6578: Amended commodity code validation.
